# Use an official Node runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app/ui

# Copy package.json and package-lock.json to the working directory
COPY ui/package*.json ./

# Install dependencies
RUN npm install

# Copy the content of the local frontend directory to the working directory
COPY ui/ .

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]
