version: '3'
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '8080:8080'
