# Use an official Golang runtime as a parent image
FROM golang:1.20

# Set the working directory in the container
WORKDIR /app/backend

# Copy the content of the local backend directory to the working directory
COPY backend/ .

# Build the backend application
RUN go build -o main .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the application
CMD ["./main"]
